[package]
name = "imap-client"
description = "Rust library to manage IMAP clients"
version = "0.2.3"
authors = ["soywod <clement.douin@posteo.net>"]
edition = "2021"
license = "MIT"
categories = ["email"]
keywords = ["email", "imap", "client"]
homepage = "https://pimalaya.org/"
documentation = "https://github.com/pimalaya/imap-client/"
repository = "https://github.com/pimalaya/imap-client/"

[features]
default = []

# TLS providers
#
tokio-rustls = ["dep:tokio-rustls", "dep:rip-starttls", "dep:rustls-platform-verifier"]
tokio-native-tls = ["dep:tokio-native-tls", "dep:rip-starttls"]

# Vendored (mostly for OpenSSL)
#
vendored = ["tokio-native-tls?/vendored"]

[dev-dependencies]
async-std = { version = "1.13", features = ["attributes"] }
imap-client = { path = ".", features = ["tokio-rustls", "tokio-native-tls"] }
static_assertions = "1.1"
tokio = { version = "1.37", features = ["full"] }

[dependencies]
imap-next = { version = "0.3", features = ["tag_generator", "ext_id", "ext_metadata"] }
rip-starttls = { version = "0.1", optional = true, features = ["tokio"] }
rustls-platform-verifier = { version = "0.5", optional = true }
thiserror = "2"
tokio = { version = "1.37", default-features = false, features = ["io-util", "net", "time"] }
tokio-native-tls = { version = "0.3", optional = true }
tokio-rustls = { version = "0.26", optional = true, default-features = false, features = ["logging", "tls12", "ring"] }
tracing = "0.1"
